# This file was generated by GoReleaser. DO NOT EDIT.
cask "aikido-dojo" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "9a65d489eecafc54dc0726189f889af32383ef0ffe54f2fa5f6cc8c156e02c13"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aac8a024c2a65f6a79213e3fa952f4119a46e079db0a32abeca47ce277247b06"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0178157fde583b3fd999c4b93322a84260d17192d08c7b0e4b7778f6b03459e4"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4e7398223df03057ccc41ff4b47ec6ac32c27df2e3a92ef9ddfc05555a14b681"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aikido-dojo"
  desc "Unofficial command-line client for the Aikido Security public API"
  homepage "https://github.com/cego/aikido-dojo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aikido-dojo"

  # No zap stanza required

  caveats <<~EOS
    aikido-dojo is not signed or notarized yet. If macOS refuses to open it after an install or upgrade, run:
      xattr -d com.apple.quarantine "$(readlink -f "$(command -v aikido-dojo)")"
  EOS
end
