# This file was generated by GoReleaser. DO NOT EDIT.
cask "aikido-dojo" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "a9250e99ca3bbd54022df19c0d6065495a23c406cd91d21977e8049b55086e8c"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "159ef9a297aa1ea7a2dfddbef9d599ba01da3ab05d3a7147df24ec0eb2340af2"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7894e02764e6fa53fceb7e5a9b93ef56546f7f84dde46afdca7a282e00e5e59e"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc685083764faa6af8d7b1d3da3ad8ffc9251debaf461a466a359d37e5bb316d"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aikido-dojo"
  desc "Unofficial command-line client for the Aikido Security public API"
  homepage "https://github.com/cego/aikido-dojo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aikido-dojo"
  bash_completion "completions/aikido-dojo.bash"
  fish_completion "completions/aikido-dojo.fish"
  zsh_completion "completions/aikido-dojo.zsh"

  # No zap stanza required

  caveats <<~EOS
    aikido-dojo is not signed or notarized yet. If macOS refuses to open it after an install or upgrade, run:
      xattr -d com.apple.quarantine "$(readlink -f "$(command -v aikido-dojo)")"
  EOS
end
