# This file was generated by GoReleaser. DO NOT EDIT.
cask "aikido-dojo" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "76b7f83f0408506942b36a1301047d53eb0fa74d198a0206a22c13c6ee37e523"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1b382fb128a9c97fc42fa9e8d8794965755db032937441ac3b203acfdfe8cc0"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "850198ee8fd95fa223ab432cd861b713ad49271f012c9a69a311d6194517a64d"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f46e0a98e705915f526e874190251f42a8c633f80ad9a73e14edcaa3a76d5692"
      url "https://github.com/cego/aikido-dojo/releases/download/v#{version}/aikido-dojo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aikido-dojo"
  desc "Unofficial command-line client for the Aikido Security public API"
  homepage "https://github.com/cego/aikido-dojo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aikido-dojo"

  # No zap stanza required

  caveats <<~EOS
    aikido-dojo is not signed or notarized yet. If macOS refuses to open it after an install or upgrade, run:
      xattr -d com.apple.quarantine "$(readlink -f "$(command -v aikido-dojo)")"
  EOS
end
